server:
  port: 8086
  context-path: /ppm-mq-recevier
 
#指定激活环境，local、sit、pro 
#默认的profile为local，其他环境通过指定启动参数使用不同的profile，比如：
#测试环境：java -jar my-spring-boot.jar --spring.profiles.active=sit
#生产环境：java -jar my-spring-boot.jar --spring.profiles.active=pro
spring:
  profiles:
    active: local
  application:
    name: ppm-mq-recevier
  
#本地环境  
---
spring:
  profiles: local
  
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
    virtualHost: /
  mail:
    host: smtp.aliyun.com
    port: 465
    username: eleadrd@aliyun.com
    password: Elead2017
    default-encoding: UTF-8
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          timeout: 25000
        starttls:
          enable: true
          required: true
        debug: true
  velocity:    
    resource-loader-path: classpath:/templates/    
    charset: UTF-8

#测试环境  
---
spring:
  profiles: sit
  
  rabbitmq:
    host: 192.168.3.57
    port: 5672
    username: elppm_user
    password: elppm
    virtualHost: /
  mail:
    host: smtp.aliyun.com
    port: 465
    username: eleadrd@aliyun.com
    password: Elead2017
    default-encoding: UTF-8
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          timeout: 25000
        starttls:
          enable: true
          required: true
        debug: true
    
#生产环境  
---
spring:
  profiles: pro
  
  rabbitmq:
    host: 119.23.124.27
    port: 5672
    username: elppm_user
    password: elppm
    virtualHost: /
  mail:
    host: smtp.aliyun.com
    port: 465
    username: eleadrd@aliyun.com
    password: Elead2017
    default-encoding: UTF-8
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          timeout: 25000
        starttls:
          enable: true
          required: true
        debug: true    